Battery Styles: Bring back good ol' circle battery style
* This code is based on the old Java implementation and converted to Kotlin

* Instead of creating different style within the same drawable
  create one on its own, this makes the code more readable and future proof

Anushek Prasal <anushekprasal@gmail.com>
- Convert to SettingsObserver
- Cleanup tuner code

CarbonROM:
- Remove broken battery entry from tuner list
- Add nullcheck for percentage

Dirty Unicorns:
- Adapt 'updateShowPercent' method to existing modifications
- Clean up code

Change-Id: I23798426e603b277408fb63f4898b385027e7eeb
Signed-off-by: PainKiller3 <ninadpatil100@gmail.com>

-----

Battery Styles: Show a bolt ⚡ when charging

Change-Id: I27f745e3458fda7c415a75d6e52f183e327cb498
Signed-off-by: PainKiller3 <ninadpatil100@gmail.com>

-----

Battery Styles: Readd dotted Circle to Kotlin impl

Change-Id: I077527d7e919a888e691f5deb29a7d3a85eaf97e

-----

Battery Styles: Hide plus when showing battery percentage inside icon

Change-Id: Iae3316dd88c69f9f4ccca6a234933a7761ec971d

-----

Battery Styles: Introduce full circle battery style

* Design based on "PA Battery" entirely rewritten in Kotlin with design adjustments

Change-Id: Ic1b74a07d645c0ccedf7015303755f6fe7a3a923

-----

Battery Styles: Remove unneeded function parameter in BatteryMeterView

- Previously, we added a boolean parameter in the updateShowPercent
function that was used for the battery percentage in the quick status bar header.
With the new battery style code, this boolean is no longer needed.
Let's remove all the code that was affected by this change.

Change-Id: I29a1b894253a67812dcd8e4c0399a0ebe837ff8a

-----

Battery options cleanup [1/2]

previously there was some logic in the Settings part that was setting text percentage style
even for the hidden style option to load the needed values in BatteryMeterView.
That made the code really hard to read and understand, and needed an additional system setting value.
Now we move the proper logic to BatteryMeterView so there's no confusion and possible glitches due to settings preferences loading,
This commit also fixes at least one glitch: while charging, set hidden style, then exit from battery options menu, then enter it again.
Before the commit it was setting the text style back.

Change-Id: Ic56196870427d11895e2d9e79413d0fcd673b7d3

-----

Battery icon: fix signal icon padding when using Hidden style

it was too far from the right corner of the screen

Change-Id: I993516c74c9a1bb6eac6d4be1e48f40ef47e60e1

-----

Battery icon: fix requestLayout() calls spam when in lockscreen

if percentage text is set outside the icon

KeyguardStatusBarView.updateVisibilities calls setForceShowPercent,
ending up calling updatePercentText
updatePercentText method gets called in many cases in BatteryMeterView
Actually i'm really busy so as a quick fix let's just skip all useless
mBatteryPercentView.setText calls

Change-Id: I82ded105248e5f7d8bce196f0a87cc51960b06cd

-----

BatteryMeterView: Fix NPE that occurs when onDensityOrFontScaleChanged() is called.

Otherwise SysUI will crash.

Tested with "Network traffic indicator".

01-07 22:27:19.805  3347  3347 E AndroidRuntime: FATAL EXCEPTION: main
01-07 22:27:19.805  3347  3347 E AndroidRuntime: Process: com.android.systemui, PID: 3347
01-07 22:27:19.805  3347  3347 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setLayoutParams(android.view.ViewGroup$LayoutParams)' on a null object reference
01-07 22:27:19.805  3347  3347 E AndroidRuntime: 	at com.android.systemui.BatteryMeterView.scaleBatteryMeterViews(BatteryMeterView.java:497)
01-07 22:27:19.805  3347  3347 E AndroidRuntime: 	at com.android.systemui.BatteryMeterView.onDensityOrFontScaleChanged(BatteryMeterView.java:437)

Signed-off-by: spezi77 <spezi7713@gmx.net>
Change-Id: Ic9378d1177a3ab8e80e1e6d6c9a064b4d626a3e2

-----

BatteryMeterView: Move null check to the beginning of the method.
Avoid unnecessary processing time when the battery icon won't get scaled anyway.

Following up: 96603a0

Signed-off-by: spezi77 <spezi7713@gmx.net>
Change-Id: Ib8b9fca0a8cb949b47f30339e6d70dc61d2215aa

-----

BatteryStatsImpl: Guard against OOB

Log:
E/BatteryExternalStatsWorker(17139): Error updating external stats:
E/BatteryExternalStatsWorker(17139): java.lang.ArrayIndexOutOfBoundsException: length=19; index=19
E/BatteryExternalStatsWorker(17139): 	at com.android.internal.os.BatteryStatsImpl.addCountLocked(BatteryStatsImpl.java:1694)
E/BatteryExternalStatsWorker(17139): 	at com.android.internal.os.BatteryStatsImpl.addCountLocked(BatteryStatsImpl.java:1682)
E/BatteryExternalStatsWorker(17139): 	at com.android.internal.os.BatteryStatsImpl.updateSystemServerThreadStats(BatteryStatsImpl.java:13459)
E/BatteryExternalStatsWorker(17139): 	at com.android.internal.os.BatteryStatsImpl.updateCpuTimeLocked(BatteryStatsImpl.java:13429)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker.updateExternalStatsLocked(BatteryExternalStatsWorker.java:656)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker.access(BatteryExternalStatsWorker.java:70)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker.run(BatteryExternalStatsWorker.java:469)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.Executors.call(Executors.java:462)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:301)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:641)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker.lambda/bin/zsh(BatteryExternalStatsWorker.java:88)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker1376351ExternalSyntheticLambda6.run(Unknown Source:2)
E/BatteryExternalStatsWorker(17139): 	at java.lang.Thread.run(Thread.java:920)

-----

QuickStatusBarHeader: Fix forbidden static imports.

QuickStatusBarHeader.java:19: error: static
import only from classes and interfaces
import static com.android.systemui.BatteryMeterView.BATTERY_STYLE_CIRCLE;

Signed-off-by: spezi77 <spezi7713@gmx.net>
Change-Id: I480372802b9708ac78d5a5d777f50cce141a590e

-----

PhoneStatusBarTransitions: Always animate battery out at the same rate

When the views are animating. When they're not, battery would still do its own fadeout.

Change-Id: I1ac01cfaf91ce32ed6b505c1e09e70374229b0d2

-----

base: SystemUI: Fix circle battery QS tinting

Battery background arc was tinted too close to differ
Replace textColorSecodary with textColorHint

[spezi77] Extended for dotted and full circle.
Signed-off-by: spezi77 <spezi7713@gmx.net>
Change-Id: I9c2d4ac0925a5678b1d9cb33072b9b5fa7902977

-----

SystemUI: Darken circle battery background on expanded QS

visually hard to tell b/g and f/g apart otherwise

fixup for 97fa8f81dc6a4ec29a093a79081c3d8b521970da

Change-Id: I581a489b14685f9c729e58a9cfb9e16de62ce155

-----

SystemUI: Adapt circle battery background to white/dark QS changes

Just reduce the f/g alpha to make the b/g. This should always work
Also apply to new header.

Change-Id: I321a5a0b315b04ba4547b246ace8a7698a3ea5cf

Co-authored-by: TheStrix <parthbhatia98@gmail.com>

fix

Change-Id: I0565d8799c0a1a05146bc23a905eda055187b6d2
Co-Authored-By: ezio84 <brabus84@gmail.com>
Co-Authored-By: Christian Oder <myself5@carbonrom.org>
Co-Authored-By: TheStrix <parthbhatia98@gmail.com>
Co-Authored-By: Nicolas Dhouailly <ndhouailly%2540gmail.com>
Co-Authored-By: spezi77 <spezi7713@gmx.net>
Co-Authored-By: Ido Ben-Hur <idoybh2@gmail.com>