SystemUI: Bring back statusbar battery styles [1/2]
Change-Id: I22f3d36746ddc551e5d96a0394ceb4a18f73b3fc

---

Revert "SystemUI: Add tuner option to show battery percentage only"

Battery styles incomming...

This reverts commit 4df6044a4b9f283592adc256730cc365bc369486.

---

Battery Styles: Bring back good ol' circle battery style

* This code is based on the old Java implementation and converted to Kotlin

* Instead of creating different style within the same drawable
  create one on its own, this makes the code more readable and future proof

Anushek Prasal <anushekprasal@gmail.com>
- Convert to SettingsObserver
- Cleanup tuner code

CarbonROM:
- Remove broken battery entry from tuner list
- Add nullcheck for percentage

Dirty Unicorns:
- Adapt 'updateShowPercent' method to existing modifications
- Clean up code

---

Battery Styles: Show a bolt ⚡ when charging

---

Battery Styles: Readd dotted Circle to Kotlin impl

---

Battery Styles: Hide plus when showing battery percentage inside icon

---

Battery Styles: Introduce full circle battery style

* Design based on "PA Battery" entirely rewritten in Kotlin with design adjustments

---

Battery Styles: Remove unneeded function parameter in BatteryMeterView

- Previously, we added a boolean parameter in the updateShowPercent
function that was used for the battery percentage in the quick status bar header.
With the new battery style code, this boolean is no longer needed.
Let's remove all the code that was affected by this change.

---

Battery options cleanup [1/2]

previously there was some logic in the Settings part that was setting text percentage style
even for the hidden style option to load the needed values in BatteryMeterView.
That made the code really hard to read and understand, and needed an additional system setting value.
Now we move the proper logic to BatteryMeterView so there's no confusion and possible glitches due to settings preferences loading,
This commit also fixes at least one glitch: while charging, set hidden style, then exit from battery options menu, then enter it again.
Before the commit it was setting the text style back.

---

Battery icon: fix signal icon padding when using Hidden style

it was too far from the right corner of the screen

---

Battery icon: fix requestLayout() calls spam when in lockscreen

if percentage text is set outside the icon

KeyguardStatusBarView.updateVisibilities calls setForceShowPercent,
ending up calling updatePercentText
updatePercentText method gets called in many cases in BatteryMeterView
Actually i'm really busy so as a quick fix let's just skip all useless
mBatteryPercentView.setText calls

---

BatteryMeterView: Fix NPE that occurs when onDensityOrFontScaleChanged() is called.

Otherwise SysUI will crash.

Tested with "Network traffic indicator".

01-07 22:27:19.805  3347  3347 E AndroidRuntime: FATAL EXCEPTION: main
01-07 22:27:19.805  3347  3347 E AndroidRuntime: Process: com.android.systemui, PID: 3347
01-07 22:27:19.805  3347  3347 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setLayoutParams(android.view.ViewGroup$LayoutParams)' on a null object reference
01-07 22:27:19.805  3347  3347 E AndroidRuntime: 	at com.android.systemui.BatteryMeterView.scaleBatteryMeterViews(BatteryMeterView.java:497)
01-07 22:27:19.805  3347  3347 E AndroidRuntime: 	at com.android.systemui.BatteryMeterView.onDensityOrFontScaleChanged(BatteryMeterView.java:437)

---

BatteryMeterView: Move null check to the beginning of the method.
Avoid unnecessary processing time when the battery icon won't get scaled anyway.

Following up: 96603a0

---

BatteryStatsImpl: Guard against OOB

Log:
E/BatteryExternalStatsWorker(17139): Error updating external stats:
E/BatteryExternalStatsWorker(17139): java.lang.ArrayIndexOutOfBoundsException: length=19; index=19
E/BatteryExternalStatsWorker(17139): 	at com.android.internal.os.BatteryStatsImpl.addCountLocked(BatteryStatsImpl.java:1694)
E/BatteryExternalStatsWorker(17139): 	at com.android.internal.os.BatteryStatsImpl.addCountLocked(BatteryStatsImpl.java:1682)
E/BatteryExternalStatsWorker(17139): 	at com.android.internal.os.BatteryStatsImpl.updateSystemServerThreadStats(BatteryStatsImpl.java:13459)
E/BatteryExternalStatsWorker(17139): 	at com.android.internal.os.BatteryStatsImpl.updateCpuTimeLocked(BatteryStatsImpl.java:13429)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker.updateExternalStatsLocked(BatteryExternalStatsWorker.java:656)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker.access(BatteryExternalStatsWorker.java:70)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker.run(BatteryExternalStatsWorker.java:469)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.Executors.call(Executors.java:462)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:301)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/BatteryExternalStatsWorker(17139): 	at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:641)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker.lambda/bin/zsh(BatteryExternalStatsWorker.java:88)
E/BatteryExternalStatsWorker(17139): 	at com.android.server.am.BatteryExternalStatsWorker1376351ExternalSyntheticLambda6.run(Unknown Source:2)
E/BatteryExternalStatsWorker(17139): 	at java.lang.Thread.run(Thread.java:920)

---

QuickStatusBarHeader: Fix forbidden static imports.

QuickStatusBarHeader.java:19: error: static
import only from classes and interfaces
import static com.android.systemui.BatteryMeterView.BATTERY_STYLE_CIRCLE;

---

PhoneStatusBarTransitions: Always animate battery out at the same rate

When the views are animating. When they're not, battery would still do its own fadeout.

---

base: SystemUI: Fix circle battery QS tinting

Battery background arc was tinted too close to differ
Replace textColorSecodary with textColorHint

[spezi77] Extended for dotted and full circle.

---

SystemUI: Darken circle battery background on expanded QS

visually hard to tell b/g and f/g apart otherwise

fixup for 97fa8f81dc6a4ec29a093a79081c3d8b521970da

---

SystemUI: Adapt circle battery background to white/dark QS changes

Just reduce the f/g alpha to make the b/g. This should always work
Also apply to new header.

---

SystemUI: Improvements for text-only battery style

Move bolt to right of percent text
Set percent text color to red in battery saver

---

SystemUI: Show battery icon in QS with text style

In text battery style, we want to hide the icon only on
the status bar. Since there's plenty of space in QS/QQS,
ensure that we always show the battery icon there.

Signed-off-by: spezi77 <spezi7713@gmx.net>
Signed-off-by: BladeRunner-A2C <john.smith@unused.email>

SystemUI: tuner: Hide battery options

As we already have custom settings for it

base: Remove aosp's 'show battery percentage' setting

This setting does nothing in yaap so let's not show it.
YAAP has it's own implementation for this setting in YASP.

Signed-off-by: Omkar Chandorkar <gotenksIN@aosip.dev>
Co-Authored-By: Adithya R <gh0strider.2k18.reborn@gmail.com>
Co-Authored-By: Christian Oder <myself5@carbonrom.org>
Co-Authored-By: ezio84 <brabus84@gmail.com>
Co-Authored-By: Ido Ben-Hur <idoybh2@gmail.com>
Co-Authored-By: Luca Stefani <luca.stefani.ge1@gmail.com>
Co-Authored-By: Nicolas Dhouailly <ndhouailly%2540gmail.com>
Co-Authored-By: spezi77 <spezi7713@gmx.net>
Co-Authored-By: TheStrix <parthbhatia98@gmail.com>